# Generated by Django 4.2.2 on 2023-08-01 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("todoapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="status",
            field=models.CharField(default="In progress", max_length=20),
        ),
    ]
