# Generated by Django 4.2.2 on 2023-07-28 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photoapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="iamge",
            new_name="image",
        ),
    ]
