# Generated by Django 4.2.2 on 2023-07-28 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photoapp", "0002_rename_iamge_photo_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="photoapp.category",
            ),
        ),
    ]
