# Generated by Django 4.2.2 on 2023-07-28 13:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photoapp", "0003_alter_photo_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="category",
            new_name="categorys",
        ),
    ]
