# Generated by Django 4.2.2 on 2023-07-28 13:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("photoapp", "0004_rename_category_photo_categorys"),
    ]

    operations = [
        migrations.RenameField(
            model_name="photo",
            old_name="categorys",
            new_name="category",
        ),
    ]
