# Generated by Django 4.2.2 on 2023-07-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retroapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="imageInput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("imageName", models.CharField(max_length=50)),
                ("imageDescription", models.CharField(max_length=500)),
                ("imageField", models.ImageField(upload_to="")),
            ],
        ),
    ]
