# Generated by Django 4.2.2 on 2023-07-28 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retroapp", "0002_imageinput"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imageinput",
            name="imageField",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
