# Generated by Django 4.2.2 on 2023-07-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("retroapp", "0003_alter_imageinput_imagefield"),
    ]

    operations = [
        migrations.AddField(
            model_name="register",
            name="last_login",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
